import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { Inter } from 'next/font/google'

import { HomePage } from '@/src/components/home/home-page';
import Footer from '@/src/components/footer/footer';
import Header from '@/src/components/header/header';

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      {/* <p>{title}</p> */}

      <HomePage data={data}/>

      
    </>
  )
}

export async function getServerSideProps(){

  const{events_categories}=await import('/data/data.json');
  console.log("hi");
  console.log(events_categories);
 
  return {
    props:{
      
      data:events_categories,
    }
  }
}
